In [2]:
import torch 
import torch.nn as nn 
import numpy  as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import time 
import math

In [ ]:

# Check if GPU is available
print(f"PyTorch version: {torch.__version__}")
print(f"GPU available: {torch.cuda.is_available()}")            
if torch.cuda.is_available():
    print(f"GPU name: {torch.cuda.get_device_name(0)}")
else:
    print("⚠️ No GPU detected. Go to Runtime → Change runtime type → GPU")
    print("   (Some demos will still work, just slower)")

print("\n✅ Setup complete! Ready to go.")

PyTorch version: 2.9.1+cpu
GPU available: False
⚠️ No GPU detected. Go to Runtime → Change runtime type → GPU
   (Some demos will still work, just slower)

✅ Setup complete! Ready to go.

In [4]:
# A scalar — just a number
scalar = torch.tensor(42.0)
print(f"Scalar: {scalar}")
print(f"  Shape: {scalar.shape}")      # torch.Size([])
print(f"  Dimensions: {scalar.dim()}")  # 0
print()

# A vector — a list of numbers
vector = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(f"Vector: {vector}")
print(f"  Shape: {vector.shape}")      # torch.Size([4])
print(f"  Dimensions: {vector.dim()}")  # 1
print()

# A matrix — a grid of numbers
matrix = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
print(f"Matrix:\n{matrix}")
print(f"  Shape: {matrix.shape}")      # torch.Size([2, 3])
print(f"  Dimensions: {matrix.dim()}")  # 2
print()

# A 3D tensor — a cube of numbers
tensor_3d = torch.zeros(2, 3, 4)
print(f"3D Tensor shape: {tensor_3d.shape}")    # [2, 3, 4]
print(f"  Dimensions: {tensor_3d.dim()}")        # 3
print()

# A 4D tensor — like a batch going through multi-head attention
tensor_4d = torch.zeros(8, 12, 3, 64)
print(f"4D Tensor shape: {tensor_4d.shape}")    # [8, 12, 3, 64]
print(f"  That's: 8 sentences × 12 heads × 3 tokens × 64 dims")

Scalar: 42.0
  Shape: torch.Size([])
  Dimensions: 0

Vector: tensor([1., 2., 3., 4.])
  Shape: torch.Size([4])
  Dimensions: 1

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
  Shape: torch.Size([2, 3])
  Dimensions: 2

3D Tensor shape: torch.Size([2, 3, 4])
  Dimensions: 3

4D Tensor shape: torch.Size([8, 12, 3, 64])
  That's: 8 sentences × 12 heads × 3 tokens × 64 dims

In [6]:
z = torch.zeros(3, 4)
print(f"Tensor z:\n{z}"
      )

Tensor z:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
o = torch.ones(3, 4 )
print(f"Tensor o:\n{o}")

Tensor o:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
r = torch.rand(3,4)
print(f"Tensor r:\n{r}")

Tensor r:
tensor([[0.4695, 0.0558, 0.1085, 0.4178],
        [0.6937, 0.5787, 0.7071, 0.4318],
        [0.5470, 0.2788, 0.5612, 0.0614]])

In [11]:
seq = torch.arange(0 ,10)
seq

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
lin = torch.linspace(0 , 1, 7)
print(lin)

tensor([0.0000, 0.1667, 0.3333, 0.5000, 0.6667, 0.8333, 1.0000])

In [15]:
# Real-world shapes in deep learning:
batch_size = 8
seq_len = 128
embed_dim = 768
num_heads = 12
head_dim = embed_dim // num_heads  # 64

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [19]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [21]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [22]:
# scaling the data 
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [24]:
X_train_tensor = torch.from_numpy(X_train_scaled)
X_test_tensor = torch.from_numpy(X_test_scaled)
y_train_tensor = torch.from_numpy(y_train_encoded)
y_test_tensor = torch.from_numpy(y_test_encoded)

In [35]:
from numpy import dtype


class MySimpleNN():

    def __init__(self , X):
        
        self.weights = torch.rand(X.shape[1] , 1 , requires_grad=True , dtype = torch.float64)
        self.bias = torch.rand(1 , dtype = torch.float64 , requires_grad=True)

    def forward(self , X):
        z = torch.matmul(X , self.weights) + self.bias
        y_pred = torch.sigmoid(z)

        return y_pred

    def loss(self , y_pred , y):
        # clamp prediction to avoid log(0) error 
        epsilon = 1e-8
        y_pred = torch.clamp(y_pred , epsilon , 1-epsilon)

        loss = -(y * torch.log(y_pred) + (1-y) * torch.log(1-y_pred))
        loss = loss.mean() #  i dont know why are we doing this but i wil find out 
        return loss

In [40]:
learning_rate = 0.1
epochs = 1000

In [41]:
X_train_tensor.shape

torch.Size([455, 30])

In [42]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.365532741316607
Epoch: 2, Loss: 3.232096588953783
Epoch: 3, Loss: 3.095058373376739
Epoch: 4, Loss: 2.9475718633271466
Epoch: 5, Loss: 2.794846163156493
Epoch: 6, Loss: 2.6393676012553504
Epoch: 7, Loss: 2.4845871573025624
Epoch: 8, Loss: 2.333884410516595
Epoch: 9, Loss: 2.184217317882972
Epoch: 10, Loss: 2.0393855529797147
Epoch: 11, Loss: 1.8974695041763132
Epoch: 12, Loss: 1.7561881254838732
Epoch: 13, Loss: 1.6207425238501598
Epoch: 14, Loss: 1.4963674025253553
Epoch: 15, Loss: 1.384046491437698
Epoch: 16, Loss: 1.2845629925171067
Epoch: 17, Loss: 1.1983948443029326
Epoch: 18, Loss: 1.1256019940197033
Epoch: 19, Loss: 1.065720463090669
Epoch: 20, Loss: 1.0176996453627982
Epoch: 21, Loss: 0.9799467489311406
Epoch: 22, Loss: 0.9505166929712696
Epoch: 23, Loss: 0.9274025448795855
Epoch: 24, Loss: 0.9088150636564919
Epoch: 25, Loss: 0.8933472535014988
Epoch: 26, Loss: 0.8799976387156528
Epoch: 27, Loss: 0.8681024452958093
Epoch: 28, Loss: 0.8572414921741852
Epoch: 29, Loss: 0.8471555649799225
Epoch: 30, Loss: 0.8376862344216273
Epoch: 31, Loss: 0.828736072103071
Epoch: 32, Loss: 0.8202437669677384
Epoch: 33, Loss: 0.8121690801172393
Epoch: 34, Loss: 0.8044839462686133
Epoch: 35, Loss: 0.797167289191602
Epoch: 36, Loss: 0.7902020330825572
Epoch: 37, Loss: 0.7835733934436246
Epoch: 38, Loss: 0.7772679062997955
Epoch: 39, Loss: 0.7712728811402029
Epoch: 40, Loss: 0.7655760967152165
Epoch: 41, Loss: 0.7601656364611757
Epoch: 42, Loss: 0.7550298047932339
Epoch: 43, Loss: 0.7501570906984183
Epoch: 44, Loss: 0.7455361592151045
Epoch: 45, Loss: 0.7411558593065513
Epoch: 46, Loss: 0.7370052410860126
Epoch: 47, Loss: 0.7330735778930284
Epoch: 48, Loss: 0.7293503902260899
Epoch: 49, Loss: 0.7258254694821892
Epoch: 50, Loss: 0.7224889000926503
Epoch: 51, Loss: 0.7193310791086366
Epoch: 52, Loss: 0.7163427326446847
Epoch: 53, Loss: 0.7135149288668985
Epoch: 54, Loss: 0.7108390874302322
Epoch: 55, Loss: 0.7083069854358501
Epoch: 56, Loss: 0.7059107601016312
Epoch: 57, Loss: 0.7036429084226251
Epoch: 58, Loss: 0.7014962841497695
Epoch: 59, Loss: 0.6994640924405041
Epoch: 60, Loss: 0.6975398825398349
Epoch: 61, Loss: 0.6957175388401753
Epoch: 62, Loss: 0.6939912706474858
Epoch: 63, Loss: 0.6923556009536735
Epoch: 64, Loss: 0.6908053544839182
Epoch: 65, Loss: 0.6893356452549054
Epoch: 66, Loss: 0.6879418638475788
Epoch: 67, Loss: 0.6866196645671152
Epoch: 68, Loss: 0.6853649526341797
Epoch: 69, Loss: 0.6841738715255093
Epoch: 70, Loss: 0.6830427905587348
Epoch: 71, Loss: 0.6819682927960459
Epoch: 72, Loss: 0.6809471633237643
Epoch: 73, Loss: 0.6799763779498983
Epoch: 74, Loss: 0.6790530923491154
Epoch: 75, Loss: 0.6781746316740045
Epoch: 76, Loss: 0.6773384806428113
Epoch: 77, Loss: 0.6765422741067234
Epoch: 78, Loss: 0.6757837880940872
Epoch: 79, Loss: 0.6750609313244105
Epoch: 80, Loss: 0.6743717371815009
Epoch: 81, Loss: 0.6737143561324076
Epoch: 82, Loss: 0.6730870485768714
Epoch: 83, Loss: 0.6724881781105957
Epoch: 84, Loss: 0.6719162051847417
Epoch: 85, Loss: 0.6713696811435229
Epoch: 86, Loss: 0.6708472426215619
Epoch: 87, Loss: 0.6703476062827064
Epoch: 88, Loss: 0.6698695638822331
Epoch: 89, Loss: 0.6694119776347475
Epoch: 90, Loss: 0.6689737758705805
Epoch: 91, Loss: 0.6685539489640697
Epoch: 92, Loss: 0.6681515455177434
Epoch: 93, Loss: 0.6677656687871091
Epoch: 94, Loss: 0.6673954733314478
Epoch: 95, Loss: 0.6670401618767309
Epoch: 96, Loss: 0.6666989823774819
Epoch: 97, Loss: 0.6663712252651163
Epoch: 98, Loss: 0.6660562208709747
Epoch: 99, Loss: 0.6657533370129481
Epoch: 100, Loss: 0.6654619767352216
Epoch: 101, Loss: 0.6651815761913092
Epoch: 102, Loss: 0.6649116026611329
Epoch: 103, Loss: 0.6646515526934734
Epoch: 104, Loss: 0.6644009503656644
Epoch: 105, Loss: 0.6641593456529107
Epoch: 106, Loss: 0.6639263129000997
Epoch: 107, Loss: 0.663701449389431
Epoch: 108, Loss: 0.6634843739976256
Epoch: 109, Loss: 0.6632747259368783
Epoch: 110, Loss: 0.6630721635741008
Epoch: 111, Loss: 0.6628763633233645
Epoch: 112, Loss: 0.6626870186067819
Epoch: 113, Loss: 0.6625038388793874
Epoch: 114, Loss: 0.6623265487138676
Epoch: 115, Loss: 0.6621548869412726
Epoch: 116, Loss: 0.6619886058440889
Epoch: 117, Loss: 0.6618274703983085
Epoch: 118, Loss: 0.6616712575613377
Epoch: 119, Loss: 0.6615197556028132
Epoch: 120, Loss: 0.6613727634755798
Epoch: 121, Loss: 0.6612300902242714
Epoch: 122, Loss: 0.6610915544291049
Epoch: 123, Loss: 0.6609569836826558
Epoch: 124, Loss: 0.6608262140975346
Epoch: 125, Loss: 0.660699089843018
Epoch: 126, Loss: 0.6605754627088184
Epoch: 127, Loss: 0.6604551916942984
Epoch: 128, Loss: 0.6603381426215423
Epoch: 129, Loss: 0.6602241877708064
Epoch: 130, Loss: 0.6601132055369656
Epoch: 131, Loss: 0.6600050801056615
Epoch: 132, Loss: 0.6598997011479454
Epoch: 133, Loss: 0.6597969635322838
Epoch: 134, Loss: 0.6596967670528743
Epoch: 135, Loss: 0.6595990161732774
Epoch: 136, Loss: 0.659503619784444
Epoch: 137, Loss: 0.6594104909762725
Epoch: 138, Loss: 0.6593195468218822
Epoch: 139, Loss: 0.65923070817385
Epoch: 140, Loss: 0.6591438994716945
Epoch: 141, Loss: 0.6590590485599467
Epoch: 142, Loss: 0.6589760865161809
Epoch: 143, Loss: 0.6588949474884229
Epoch: 144, Loss: 0.6588155685413886
Epoch: 145, Loss: 0.6587378895110368
Epoch: 146, Loss: 0.6586618528669582
Epoch: 147, Loss: 0.6585874035821448
Epoch: 148, Loss: 0.6585144890097201
Epoch: 149, Loss: 0.6584430587662264
Epoch: 150, Loss: 0.6583730646211028
Epoch: 151, Loss: 0.658304460391995
Epoch: 152, Loss: 0.6582372018455743
Epoch: 153, Loss: 0.6581712466035505
Epoch: 154, Loss: 0.6581065540535916
Epoch: 155, Loss: 0.6580430852648739
Epoch: 156, Loss: 0.6579808029080059
Epoch: 157, Loss: 0.6579196711790855
Epoch: 158, Loss: 0.6578596557276586
Epoch: 159, Loss: 0.6578007235883706
Epoch: 160, Loss: 0.6577428431161028
Epoch: 161, Loss: 0.6576859839244077
Epoch: 162, Loss: 0.6576301168270633
Epoch: 163, Loss: 0.6575752137825773
Epoch: 164, Loss: 0.657521247841482
Epoch: 165, Loss: 0.6574681930962719
Epoch: 166, Loss: 0.6574160246338392
Epoch: 167, Loss: 0.6573647184902796
Epoch: 168, Loss: 0.6573142516079363
Epoch: 169, Loss: 0.6572646017945701
Epoch: 170, Loss: 0.6572157476845375
Epoch: 171, Loss: 0.6571676687018769
Epoch: 172, Loss: 0.6571203450251987
Epoch: 173, Loss: 0.6570737575542897
Epoch: 174, Loss: 0.6570278878783374
Epoch: 175, Loss: 0.656982718245695
Epoch: 176, Loss: 0.6569382315351054
Epoch: 177, Loss: 0.6568944112283099
Epoch: 178, Loss: 0.6568512413839698
Epoch: 179, Loss: 0.656808706612835
Epoch: 180, Loss: 0.6567667920540946
Epoch: 181, Loss: 0.6567254833528521
Epoch: 182, Loss: 0.6566847666386653
Epoch: 183, Loss: 0.6566446285050979
Epoch: 184, Loss: 0.6566050559902356
Epoch: 185, Loss: 0.6565660365581119
Epoch: 186, Loss: 0.6565275580810037
Epoch: 187, Loss: 0.6564896088225509
Epoch: 188, Loss: 0.6564521774216593
Epoch: 189, Loss: 0.6564152528771479
Epoch: 190, Loss: 0.6563788245331049
Epoch: 191, Loss: 0.6563428820649163
Epoch: 192, Loss: 0.6563074154659346
Epoch: 193, Loss: 0.6562724150347558
Epoch: 194, Loss: 0.6562378713630769
Epoch: 195, Loss: 0.6562037753241013
Epoch: 196, Loss: 0.656170118061472
Epoch: 197, Loss: 0.6561368909787004
Epoch: 198, Loss: 0.6561040857290709
Epoch: 199, Loss: 0.656071694205998
Epoch: 200, Loss: 0.6560397085338122
Epoch: 201, Loss: 0.6560081210589557
Epoch: 202, Loss: 0.6559769243415688
Epoch: 203, Loss: 0.6559461111474464
Epoch: 204, Loss: 0.65591567444035
Epoch: 205, Loss: 0.6558856073746542
Epoch: 206, Loss: 0.6558559032883151
Epoch: 207, Loss: 0.6558265556961473
Epoch: 208, Loss: 0.6557975582833875
Epoch: 209, Loss: 0.655768904899539
Epoch: 210, Loss: 0.6557405895524817
Epoch: 211, Loss: 0.6557126064028308
Epoch: 212, Loss: 0.655684949758541
Epoch: 213, Loss: 0.655657614069736
Epoch: 214, Loss: 0.6556305939237591
Epoch: 215, Loss: 0.6556038840404328
Epoch: 216, Loss: 0.6555774792675154
Epoch: 217, Loss: 0.6555513745763503
Epoch: 218, Loss: 0.6555255650576938
Epoch: 219, Loss: 0.6555000459177183
Epoch: 220, Loss: 0.6554748124741788
Epoch: 221, Loss: 0.6554498601527388
Epoch: 222, Loss: 0.655425184483443
Epoch: 223, Loss: 0.6554007810973387
Epoch: 224, Loss: 0.6553766457232296
Epoch: 225, Loss: 0.6553527741845636
Epoch: 226, Loss: 0.6553291623964433
Epoch: 227, Loss: 0.6553058063627589
Epoch: 228, Loss: 0.6552827021734315
Epoch: 229, Loss: 0.6552598460017686
Epoch: 230, Loss: 0.6552372341019211
Epoch: 231, Loss: 0.6552148628064428
Epoch: 232, Loss: 0.6551927285239418
Epoch: 233, Loss: 0.6551708277368254
Epoch: 234, Loss: 0.6551491569991303
Epoch: 235, Loss: 0.6551277129344366
Epoch: 236, Loss: 0.6551064922338614
Epoch: 237, Loss: 0.655085491654128
Epoch: 238, Loss: 0.6550647080157077
Epoch: 239, Loss: 0.6550441382010318
Epoch: 240, Loss: 0.6550237791527701
Epoch: 241, Loss: 0.6550036278721713
Epoch: 242, Loss: 0.6549836814174674
Epoch: 243, Loss: 0.6549639369023339
Epoch: 244, Loss: 0.6549443914944069
Epoch: 245, Loss: 0.6549250424138534
Epoch: 246, Loss: 0.6549058869319927
Epoch: 247, Loss: 0.6548869223699676
Epoch: 248, Loss: 0.6548681460974611
Epoch: 249, Loss: 0.65484955553146
Epoch: 250, Loss: 0.654831148135059
Epoch: 251, Loss: 0.6548129214163095
Epoch: 252, Loss: 0.6547948729271045
Epoch: 253, Loss: 0.654777000262104
Epoch: 254, Loss: 0.6547593010576954
Epoch: 255, Loss: 0.6547417729909903
Epoch: 256, Loss: 0.6547244137788522
Epoch: 257, Loss: 0.6547072211769586
Epoch: 258, Loss: 0.6546901929788932
Epoch: 259, Loss: 0.6546733270152681
Epoch: 260, Loss: 0.6546566211528729
Epoch: 261, Loss: 0.6546400732938519
Epoch: 262, Loss: 0.6546236813749086
Epoch: 263, Loss: 0.6546074433665333
Epoch: 264, Loss: 0.6545913572722566
Epoch: 265, Loss: 0.6545754211279243
Epoch: 266, Loss: 0.6545596330009956
Epoch: 267, Loss: 0.6545439909898634
Epoch: 268, Loss: 0.6545284932231934
Epoch: 269, Loss: 0.6545131378592843
Epoch: 270, Loss: 0.6544979230854465
Epoch: 271, Loss: 0.6544828471173992
Epoch: 272, Loss: 0.6544679081986849
Epoch: 273, Loss: 0.6544531046001013
Epoch: 274, Loss: 0.6544384346191486
Epoch: 275, Loss: 0.6544238965794936
Epoch: 276, Loss: 0.6544094888304484
Epoch: 277, Loss: 0.6543952097464626
Epoch: 278, Loss: 0.6543810577266316
Epoch: 279, Loss: 0.6543670311942169
Epoch: 280, Loss: 0.6543531285961794
Epoch: 281, Loss: 0.654339348402726
Epoch: 282, Loss: 0.6543256891068676
Epoch: 283, Loss: 0.6543121492239893
Epoch: 284, Loss: 0.6542987272914311
Epoch: 285, Loss: 0.654285421868081
Epoch: 286, Loss: 0.6542722315339762
Epoch: 287, Loss: 0.6542591548899159
Epoch: 288, Loss: 0.6542461905570847
Epoch: 289, Loss: 0.654233337176683
Epoch: 290, Loss: 0.6542205934095688
Epoch: 291, Loss: 0.6542079579359072
Epoch: 292, Loss: 0.6541954294548281
Epoch: 293, Loss: 0.6541830066840929
Epoch: 294, Loss: 0.6541706883597692
Epoch: 295, Loss: 0.654158473235912
Epoch: 296, Loss: 0.6541463600842541
Epoch: 297, Loss: 0.6541343476939016
Epoch: 298, Loss: 0.6541224348710387
Epoch: 299, Loss: 0.6541106204386374
Epoch: 300, Loss: 0.6540989032361746
Epoch: 301, Loss: 0.654087282119355
Epoch: 302, Loss: 0.654075755959841
Epoch: 303, Loss: 0.6540643236449879
Epoch: 304, Loss: 0.6540529840775845
Epoch: 305, Loss: 0.6540417361756005
Epoch: 306, Loss: 0.6540305788719376
Epoch: 307, Loss: 0.6540195111141879
Epoch: 308, Loss: 0.6540085318643959
Epoch: 309, Loss: 0.653997640098826
Epoch: 310, Loss: 0.6539868348077345
Epoch: 311, Loss: 0.6539761149951462
Epoch: 312, Loss: 0.6539654796786378
Epoch: 313, Loss: 0.6539549278891206
Epoch: 314, Loss: 0.6539444586706336
Epoch: 315, Loss: 0.653934071080136
Epoch: 316, Loss: 0.6539237641873064
Epoch: 317, Loss: 0.6539135370743451
Epoch: 318, Loss: 0.6539033888357801
Epoch: 319, Loss: 0.6538933185782767
Epoch: 320, Loss: 0.653883325420452
Epoch: 321, Loss: 0.6538734084926914
Epoch: 322, Loss: 0.6538635669369687
Epoch: 323, Loss: 0.6538537999066713
Epoch: 324, Loss: 0.6538441065664261
Epoch: 325, Loss: 0.653834486091931
Epoch: 326, Loss: 0.6538249376697872
Epoch: 327, Loss: 0.6538154604973375
Epoch: 328, Loss: 0.6538060537825039
Epoch: 329, Loss: 0.6537967167436314
Epoch: 330, Loss: 0.6537874486093324
Epoch: 331, Loss: 0.6537782486183354
Epoch: 332, Loss: 0.6537691160193353
Epoch: 333, Loss: 0.6537600500708461
Epoch: 334, Loss: 0.6537510500410585
Epoch: 335, Loss: 0.6537421152076964
Epoch: 336, Loss: 0.6537332448578783
Epoch: 337, Loss: 0.6537244382879814
Epoch: 338, Loss: 0.6537156948035059
Epoch: 339, Loss: 0.6537070137189436
Epoch: 340, Loss: 0.6536983943576478
Epoch: 341, Loss: 0.653689836051705
Epoch: 342, Loss: 0.6536813381418108
Epoch: 343, Loss: 0.6536728999771444
Epoch: 344, Loss: 0.6536645209152483
Epoch: 345, Loss: 0.6536562003219092
Epoch: 346, Loss: 0.6536479375710393
Epoch: 347, Loss: 0.6536397320445617
Epoch: 348, Loss: 0.6536315831322962
Epoch: 349, Loss: 0.6536234902318477
Epoch: 350, Loss: 0.653615452748496
Epoch: 351, Loss: 0.6536074700950875
Epoch: 352, Loss: 0.6535995416919289
Epoch: 353, Loss: 0.653591666966682
Epoch: 354, Loss: 0.6535838453542605
Epoch: 355, Loss: 0.653576076296729
Epoch: 356, Loss: 0.6535683592432022
Epoch: 357, Loss: 0.6535606936497473
Epoch: 358, Loss: 0.6535530789792865
Epoch: 359, Loss: 0.653545514701502
Epoch: 360, Loss: 0.6535380002927426
Epoch: 361, Loss: 0.65353053523593
Epoch: 362, Loss: 0.6535231190204689
Epoch: 363, Loss: 0.6535157511421574
Epoch: 364, Loss: 0.6535084311030981
Epoch: 365, Loss: 0.653501158411612
Epoch: 366, Loss: 0.6534939325821522
Epoch: 367, Loss: 0.6534867531352204
Epoch: 368, Loss: 0.6534796195972833
Epoch: 369, Loss: 0.6534725315006914
Epoch: 370, Loss: 0.6534654883835984
Epoch: 371, Loss: 0.6534584897898814
Epoch: 372, Loss: 0.6534515352690636
Epoch: 373, Loss: 0.653444624376237
Epoch: 374, Loss: 0.6534377566719867
Epoch: 375, Loss: 0.6534309317223158
Epoch: 376, Loss: 0.6534241490985732
Epoch: 377, Loss: 0.653417408377379
Epoch: 378, Loss: 0.6534107091405554
Epoch: 379, Loss: 0.653404050975055
Epoch: 380, Loss: 0.6533974334728916
Epoch: 381, Loss: 0.6533908562310724
Epoch: 382, Loss: 0.6533843188515306
Epoch: 383, Loss: 0.6533778209410589
Epoch: 384, Loss: 0.653371362111244
Epoch: 385, Loss: 0.6533649419784031
Epoch: 386, Loss: 0.653358560163519
Epoch: 387, Loss: 0.6533522162921794
Epoch: 388, Loss: 0.6533459099945137
Epoch: 389, Loss: 0.6533396409051329
Epoch: 390, Loss: 0.6533334086630702
Epoch: 391, Loss: 0.653327212911721
Epoch: 392, Loss: 0.6533210532987859
Epoch: 393, Loss: 0.653314929476212
Epoch: 394, Loss: 0.653308841100138
Epoch: 395, Loss: 0.6533027878308375
Epoch: 396, Loss: 0.6532967693326638
Epoch: 397, Loss: 0.6532907852739973
Epoch: 398, Loss: 0.6532848353271906
Epoch: 399, Loss: 0.6532789191685165
Epoch: 400, Loss: 0.6532730364781166
Epoch: 401, Loss: 0.6532671869399492
Epoch: 402, Loss: 0.6532613702417407
Epoch: 403, Loss: 0.6532555860749332
Epoch: 404, Loss: 0.6532498341346379
Epoch: 405, Loss: 0.6532441141195868
Epoch: 406, Loss: 0.653238425732083
Epoch: 407, Loss: 0.653232768677956
Epoch: 408, Loss: 0.6532271426665143
Epoch: 409, Loss: 0.6532215474105002
Epoch: 410, Loss: 0.6532159826260445
Epoch: 411, Loss: 0.6532104480326225
Epoch: 412, Loss: 0.6532049433530102
Epoch: 413, Loss: 0.6531994683132406
Epoch: 414, Loss: 0.6531940226425621
Epoch: 415, Loss: 0.6531886060733965
Epoch: 416, Loss: 0.6531832183412966
Epoch: 417, Loss: 0.6531778591849063
Epoch: 418, Loss: 0.6531725283459211
Epoch: 419, Loss: 0.653167225569046
Epoch: 420, Loss: 0.6531619506019598
Epoch: 421, Loss: 0.6531567031952735
Epoch: 422, Loss: 0.6531514831024942
Epoch: 423, Loss: 0.6531462900799864
Epoch: 424, Loss: 0.6531411238869363
Epoch: 425, Loss: 0.6531359842853139
Epoch: 426, Loss: 0.6531308710398384
Epoch: 427, Loss: 0.6531257839179413
Epoch: 428, Loss: 0.6531207226897329
Epoch: 429, Loss: 0.6531156871279667
Epoch: 430, Loss: 0.653110677008006
Epoch: 431, Loss: 0.6531056921077899
Epoch: 432, Loss: 0.6531007322078003
Epoch: 433, Loss: 0.6530957970910296
Epoch: 434, Loss: 0.653090886542948
Epoch: 435, Loss: 0.6530860003514724
Epoch: 436, Loss: 0.6530811383069339
Epoch: 437, Loss: 0.6530763002020484
Epoch: 438, Loss: 0.653071485831885
Epoch: 439, Loss: 0.6530666949938361
Epoch: 440, Loss: 0.6530619274875883
Epoch: 441, Loss: 0.6530571831150923
Epoch: 442, Loss: 0.6530524616805353
Epoch: 443, Loss: 0.6530477629903111
Epoch: 444, Loss: 0.6530430868529927
Epoch: 445, Loss: 0.6530384330793049
Epoch: 446, Loss: 0.6530338014820963
Epoch: 447, Loss: 0.653029191876313
Epoch: 448, Loss: 0.6530246040789714
Epoch: 449, Loss: 0.6530200379091325
Epoch: 450, Loss: 0.6530154931878757
Epoch: 451, Loss: 0.6530109697382733
Epoch: 452, Loss: 0.6530064673853657
Epoch: 453, Loss: 0.6530019859561358
Epoch: 454, Loss: 0.6529975252794848
Epoch: 455, Loss: 0.6529930851862092
Epoch: 456, Loss: 0.6529886655089744
Epoch: 457, Loss: 0.6529842660822939
Epoch: 458, Loss: 0.6529798867425041
Epoch: 459, Loss: 0.6529755273277421
Epoch: 460, Loss: 0.652971187677924
Epoch: 461, Loss: 0.6529668676347204
Epoch: 462, Loss: 0.6529625670415371
Epoch: 463, Loss: 0.6529582857434907
Epoch: 464, Loss: 0.6529540235873897
Epoch: 465, Loss: 0.6529497804217113
Epoch: 466, Loss: 0.6529455560965817
Epoch: 467, Loss: 0.6529413504637557
Epoch: 468, Loss: 0.6529371633765949
Epoch: 469, Loss: 0.6529329946900502
Epoch: 470, Loss: 0.6529288442606392
Epoch: 471, Loss: 0.6529247119464291
Epoch: 472, Loss: 0.6529205976070158
Epoch: 473, Loss: 0.6529165011035057
Epoch: 474, Loss: 0.6529124222984972
Epoch: 475, Loss: 0.6529083610560614
Epoch: 476, Loss: 0.6529043172417247
Epoch: 477, Loss: 0.6529002907224503
Epoch: 478, Loss: 0.6528962813666203
Epoch: 479, Loss: 0.6528922890440187
Epoch: 480, Loss: 0.6528883136258141
Epoch: 481, Loss: 0.6528843549845421
Epoch: 482, Loss: 0.6528804129940887
Epoch: 483, Loss: 0.6528764875296744
Epoch: 484, Loss: 0.6528725784678362
Epoch: 485, Loss: 0.6528686856864129
Epoch: 486, Loss: 0.6528648090645287
Epoch: 487, Loss: 0.6528609484825776
Epoch: 488, Loss: 0.652857103822207
Epoch: 489, Loss: 0.6528532749663032
Epoch: 490, Loss: 0.6528494617989766
Epoch: 491, Loss: 0.6528456642055454
Epoch: 492, Loss: 0.6528418820725221
Epoch: 493, Loss: 0.6528381152875985
Epoch: 494, Loss: 0.6528343637396312
Epoch: 495, Loss: 0.6528306273186277
Epoch: 496, Loss: 0.6528269059157324
Epoch: 497, Loss: 0.6528231994232124
Epoch: 498, Loss: 0.6528195077344443
Epoch: 499, Loss: 0.6528158307439006
Epoch: 500, Loss: 0.6528121683471363
Epoch: 501, Loss: 0.6528085204407764
Epoch: 502, Loss: 0.652804886922502
Epoch: 503, Loss: 0.6528012676910385
Epoch: 504, Loss: 0.6527976626461421
Epoch: 505, Loss: 0.6527940716885883
Epoch: 506, Loss: 0.6527904947201587
Epoch: 507, Loss: 0.6527869316436299
Epoch: 508, Loss: 0.6527833823627606
Epoch: 509, Loss: 0.6527798467822804
Epoch: 510, Loss: 0.6527763248078783
Epoch: 511, Loss: 0.6527728163461901
Epoch: 512, Loss: 0.6527693213047885
Epoch: 513, Loss: 0.6527658395921712
Epoch: 514, Loss: 0.6527623711177497
Epoch: 515, Loss: 0.6527589157918386
Epoch: 516, Loss: 0.652755473525645
Epoch: 517, Loss: 0.652752044231258
Epoch: 518, Loss: 0.6527486278216369
Epoch: 519, Loss: 0.6527452242106031
Epoch: 520, Loss: 0.652741833312828
Epoch: 521, Loss: 0.6527384550438233
Epoch: 522, Loss: 0.6527350893199321
Epoch: 523, Loss: 0.6527317360583176
Epoch: 524, Loss: 0.6527283951769546
Epoch: 525, Loss: 0.6527250665946184
Epoch: 526, Loss: 0.6527217502308776
Epoch: 527, Loss: 0.6527184460060828
Epoch: 528, Loss: 0.6527151538413583
Epoch: 529, Loss: 0.6527118736585924
Epoch: 530, Loss: 0.6527086053804293
Epoch: 531, Loss: 0.6527053489302594
Epoch: 532, Loss: 0.6527021042322112
Epoch: 533, Loss: 0.6526988712111421
Epoch: 534, Loss: 0.6526956497926301
Epoch: 535, Loss: 0.6526924399029652
Epoch: 536, Loss: 0.6526892414691423
Epoch: 537, Loss: 0.6526860544188506
Epoch: 538, Loss: 0.6526828786804678
Epoch: 539, Loss: 0.6526797141830509
Epoch: 540, Loss: 0.6526765608563284
Epoch: 541, Loss: 0.652673418630693
Epoch: 542, Loss: 0.6526702874371935
Epoch: 543, Loss: 0.6526671672075269
Epoch: 544, Loss: 0.6526640578740318
Epoch: 545, Loss: 0.6526609593696804

In [56]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.2).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"accuracy : {accuracy.item()}")

accuracy : 0.4385964870452881

In [63]:
# tensor GPU operations 
torch.cuda.is_available()


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

a = torch.tensor([1.0, 2.0, 3.0], device=device)
# this is how to create a tenso on GPU 
b = torch.tensor([1.0, 2.0, 3.0], device=device)


a.to(device)

cpu

tensor([1., 2., 3.])

In [67]:
b = torch.rand(2,3,4)

b = b.permute(2, 0 ,1)

b.shape

torch.Size([4, 2, 3])

In [70]:
# autodgrad in pytorch in python 
# provides a new way to compute gradients that means : it provides automatic gradients computation for tensor operations 
# it enables graduesbt computation which is essential forthe training ml model using the optimization algorithms like gradient desent 

X = torch.tensor([[1.0, 2.0], [3.0, 4.0]], requires_grad=True)
x = torch.tensor(3.0, requires_grad=True)
y = x**2

In [71]:
y.backward()

In [72]:
x.grad

tensor(6.)

In [73]:
import torch

# Inputs
x = torch.tensor(6.7)  # Input feature
y = torch.tensor(0.0)  # True label (binary)

w = torch.tensor(1.0)  # Weight
b = torch.tensor(0.0)  # Bias

In [74]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8  # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
    return -(target * torch.log(prediction) + (1 - target) * torch.log(1 - prediction))

In [75]:
# Forward pass
z = w * x + b  # Weighted sum (linear part)
y_pred = torch.sigmoid(z)  # Predicted probability

# Compute binary cross-entropy loss
loss = binary_cross_entropy_loss(y_pred, y)

In [76]:
# Derivatives:
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x  # dz/dw = x
dz_db = 1  # dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [77]:
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218

In [78]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)

In [79]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [82]:
z = w*x + b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [83]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [84]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [86]:
loss.backward()

In [87]:
w.grad

tensor(6.6918)

In [88]:
b.grad

tensor(0.9988)

In [89]:
# options to clear the gradients  : why ? beacuse they consume memory for large models and also prevent the gradient accumulation 
# clearing grad
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [90]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [91]:
y.backward()

In [92]:
x.grad

tensor(4.)

In [93]:
x.grad.zero_()

tensor(0.)

In [94]:
# disable gradient tracking
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [95]:
y = x ** 2
y

tensor(4., grad_fn=<PowBackward0>)

In [96]:
y.backward()

x.grad

tensor(4.)

In [97]:
# there are 3 ways to clean the gradients : # option 1 - requires_grad_(False)
# option 2 - detach()
# option 3 - torch.no_grad()

In [99]:
x.requires_grad_(False)

tensor(2.)

In [104]:
x.detach()

tensor(2.)

In [107]:
y.detach()

y.requires_grad

True

### learning about the nn module

In [126]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features , 1  )
    self.sigmoid = nn.Sigmoid()

  def forward(self , features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [127]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features) 
model(features)

# notice we are not doing this model.forward(features) but we are doing this model(features)

tensor([[0.4666],
        [0.5421],
        [0.5126],
        [0.5069],
        [0.5088],
        [0.4758],
        [0.4586],
        [0.4578],
        [0.4551],
        [0.4930]], grad_fn=<SigmoidBackward0>)

In [129]:
model.linear.weight

Parameter containing:
tensor([[-0.3855,  0.3159,  0.2854, -0.0171,  0.0716]], requires_grad=True)

In [130]:
model.linear.bias

Parameter containing:
tensor([-0.2006], requires_grad=True)

In [131]:
# torchinfo 

from torchinfo import summary

summary(model , input_size = (10 , 5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

### changing the setup

In [133]:
# 5 inputs ----> 3 neurons ----> 1 neuron ----> 1 output 
# let's implement this using the nn module

In [140]:
class MyNewNN(nn.Module):

    def __init__(self, num_features):

        super().__init__()
        self.linear1 = nn.Linear(num_features , 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()


    def forward(self , features):

        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [141]:
# create dataset
features = torch.rand(10,5)

# create model
model = MyNewNN(features.shape[1])

# call model for forward pass
# model.forward(features) 
model(features)

tensor([[0.5659],
        [0.5448],
        [0.5614],
        [0.5581],
        [0.5842],
        [0.5798],
        [0.5451],
        [0.5581],
        [0.5842],
        [0.5843]], grad_fn=<SigmoidBackward0>)

In [143]:
model.linear1.weight

Parameter containing:
tensor([[-0.1989, -0.3464,  0.2463, -0.0299, -0.1531],
        [ 0.0101,  0.0451, -0.2301,  0.2007, -0.1498],
        [-0.1211, -0.1956,  0.2753,  0.2575,  0.3027]], requires_grad=True)

In [147]:
model.linear2.bias

Parameter containing:
tensor([0.3402], requires_grad=True)